version: '3.9'

services:
  resume-site:
    build: Dockerfile.prod
    container_name: collectivops-site-nginx
    restart: "unless-stopped"
    ports:
      - "8086:80"
    networks:
      - private
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.resume-site.rule=Host(`collectivops.net`) || Host(`collectivops.org`) || Host(`www.collectivops.net`) || Host(`www.collectivops.org`)"
      - "traefik.http.routers.resume-site.entrypoints=websecure"
      - "traefik.http.services.resume-site.loadbalancer.server.port=80"
      - "traefik.http.routers.resume-site.tls.certresolver=myresolver"
      - "traefik.http.middlewares.temp-redirect.redirectregex.regex=^(https?://)(.*).collectivops.org/(.*)"
      - "traefik.http.middlewares.temp-redirect.redirectregex.replacement=$${1}.collectiveops.net/$${3}"
      - "traefik.http.routers.resume-site.middlewares=temp-redirect"

networks:
  private:
    external: true
    name: Private

